/**
 * GENERATED by scripts/bake_thread_textures.py from the photo references in raw/assets/ — do
 * not hand-edit; re-run the script after changing sources or crop specs. Every texture is a
 * pair of GRAYSCALE luminance PNGs (hue never ships — see the Q18 note on thread.texture in
 * core/theme.ts): `multiply` darkens a string's data tint into the rope's grooves, `screen`
 * adds the crest highlights multiply cannot reach. The registry feeds the prototype's
 * "Thread" dropdown; keys are its stable option values.
 */
import type { ThemeImageLuminanceTexture } from "../theme";
export declare const THREAD_TEXTURES: Record<string, {
    name: string;
    texture: ThemeImageLuminanceTexture;
}>;
